// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/store.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyQuery struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyQuery) Reset()         { *m = EmptyQuery{} }
func (m *EmptyQuery) String() string { return proto.CompactTextString(m) }
func (*EmptyQuery) ProtoMessage()    {}
func (*EmptyQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{0}
}

func (m *EmptyQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyQuery.Unmarshal(m, b)
}
func (m *EmptyQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyQuery.Marshal(b, m, deterministic)
}
func (m *EmptyQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyQuery.Merge(m, src)
}
func (m *EmptyQuery) XXX_Size() int {
	return xxx_messageInfo_EmptyQuery.Size(m)
}
func (m *EmptyQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyQuery.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyQuery proto.InternalMessageInfo

func (m *EmptyQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type BookQuery struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookQuery) Reset()         { *m = BookQuery{} }
func (m *BookQuery) String() string { return proto.CompactTextString(m) }
func (*BookQuery) ProtoMessage()    {}
func (*BookQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{1}
}

func (m *BookQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookQuery.Unmarshal(m, b)
}
func (m *BookQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookQuery.Marshal(b, m, deterministic)
}
func (m *BookQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookQuery.Merge(m, src)
}
func (m *BookQuery) XXX_Size() int {
	return xxx_messageInfo_BookQuery.Size(m)
}
func (m *BookQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BookQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BookQuery proto.InternalMessageInfo

func (m *BookQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBookRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRes) Reset()         { *m = DeleteBookRes{} }
func (m *DeleteBookRes) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRes) ProtoMessage()    {}
func (*DeleteBookRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{2}
}

func (m *DeleteBookRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRes.Unmarshal(m, b)
}
func (m *DeleteBookRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRes.Marshal(b, m, deterministic)
}
func (m *DeleteBookRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRes.Merge(m, src)
}
func (m *DeleteBookRes) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRes.Size(m)
}
func (m *DeleteBookRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRes proto.InternalMessageInfo

func (m *DeleteBookRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type BookAuthor struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookAuthor) Reset()         { *m = BookAuthor{} }
func (m *BookAuthor) String() string { return proto.CompactTextString(m) }
func (*BookAuthor) ProtoMessage()    {}
func (*BookAuthor) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{3}
}

func (m *BookAuthor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookAuthor.Unmarshal(m, b)
}
func (m *BookAuthor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookAuthor.Marshal(b, m, deterministic)
}
func (m *BookAuthor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookAuthor.Merge(m, src)
}
func (m *BookAuthor) XXX_Size() int {
	return xxx_messageInfo_BookAuthor.Size(m)
}
func (m *BookAuthor) XXX_DiscardUnknown() {
	xxx_messageInfo_BookAuthor.DiscardUnknown(m)
}

var xxx_messageInfo_BookAuthor proto.InternalMessageInfo

func (m *BookAuthor) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *BookAuthor) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UpdateBookReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Book                 *Book    `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookReq) Reset()         { *m = UpdateBookReq{} }
func (m *UpdateBookReq) String() string { return proto.CompactTextString(m) }
func (*UpdateBookReq) ProtoMessage()    {}
func (*UpdateBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{4}
}

func (m *UpdateBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookReq.Unmarshal(m, b)
}
func (m *UpdateBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookReq.Marshal(b, m, deterministic)
}
func (m *UpdateBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookReq.Merge(m, src)
}
func (m *UpdateBookReq) XXX_Size() int {
	return xxx_messageInfo_UpdateBookReq.Size(m)
}
func (m *UpdateBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookReq proto.InternalMessageInfo

func (m *UpdateBookReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateBookReq) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type BookReq struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookReq) Reset()         { *m = BookReq{} }
func (m *BookReq) String() string { return proto.CompactTextString(m) }
func (*BookReq) ProtoMessage()    {}
func (*BookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{5}
}

func (m *BookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookReq.Unmarshal(m, b)
}
func (m *BookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookReq.Marshal(b, m, deterministic)
}
func (m *BookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookReq.Merge(m, src)
}
func (m *BookReq) XXX_Size() int {
	return xxx_messageInfo_BookReq.Size(m)
}
func (m *BookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookReq proto.InternalMessageInfo

func (m *BookReq) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type BookRes struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookRes) Reset()         { *m = BookRes{} }
func (m *BookRes) String() string { return proto.CompactTextString(m) }
func (*BookRes) ProtoMessage()    {}
func (*BookRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{6}
}

func (m *BookRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRes.Unmarshal(m, b)
}
func (m *BookRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRes.Marshal(b, m, deterministic)
}
func (m *BookRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRes.Merge(m, src)
}
func (m *BookRes) XXX_Size() int {
	return xxx_messageInfo_BookRes.Size(m)
}
func (m *BookRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRes.DiscardUnknown(m)
}

var xxx_messageInfo_BookRes proto.InternalMessageInfo

func (m *BookRes) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type Book struct {
	Id                   string      `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author               *BookAuthor `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	ReleaseYear          int32       `protobuf:"varint,5,opt,name=releaseYear,proto3" json:"releaseYear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{7}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Book) GetAuthor() *BookAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Book) GetReleaseYear() int32 {
	if m != nil {
		return m.ReleaseYear
	}
	return 0
}

type BookList struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookList) Reset()         { *m = BookList{} }
func (m *BookList) String() string { return proto.CompactTextString(m) }
func (*BookList) ProtoMessage()    {}
func (*BookList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{8}
}

func (m *BookList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookList.Unmarshal(m, b)
}
func (m *BookList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookList.Marshal(b, m, deterministic)
}
func (m *BookList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookList.Merge(m, src)
}
func (m *BookList) XXX_Size() int {
	return xxx_messageInfo_BookList.Size(m)
}
func (m *BookList) XXX_DiscardUnknown() {
	xxx_messageInfo_BookList.DiscardUnknown(m)
}

var xxx_messageInfo_BookList proto.InternalMessageInfo

func (m *BookList) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyQuery)(nil), "proto.EmptyQuery")
	proto.RegisterType((*BookQuery)(nil), "proto.BookQuery")
	proto.RegisterType((*DeleteBookRes)(nil), "proto.DeleteBookRes")
	proto.RegisterType((*BookAuthor)(nil), "proto.BookAuthor")
	proto.RegisterType((*UpdateBookReq)(nil), "proto.UpdateBookReq")
	proto.RegisterType((*BookReq)(nil), "proto.BookReq")
	proto.RegisterType((*BookRes)(nil), "proto.BookRes")
	proto.RegisterType((*Book)(nil), "proto.Book")
	proto.RegisterType((*BookList)(nil), "proto.BookList")
}

func init() { proto.RegisterFile("proto/store.proto", fileDescriptor_3f39e0831e20e871) }

var fileDescriptor_3f39e0831e20e871 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x8e, 0xda, 0x40,
	0x0c, 0xc6, 0x49, 0x48, 0x16, 0x70, 0xb4, 0xdb, 0xae, 0xb5, 0x87, 0x88, 0x56, 0x6a, 0x3a, 0xa7,
	0xdd, 0x4a, 0x50, 0x09, 0xaa, 0x9e, 0x4b, 0xff, 0x21, 0xa4, 0x5e, 0x1a, 0xa9, 0x87, 0x1e, 0x03,
	0x71, 0xdb, 0x88, 0xc0, 0x84, 0x99, 0xe1, 0xc0, 0x43, 0xf4, 0x09, 0xfa, 0xb2, 0xd5, 0x38, 0x09,
	0x09, 0x08, 0x89, 0x53, 0x62, 0x7f, 0x3f, 0x8f, 0xed, 0x99, 0x0f, 0xee, 0x0b, 0x25, 0x8d, 0x7c,
	0xab, 0x8d, 0x54, 0x34, 0xe6, 0x7f, 0xf4, 0xf9, 0x23, 0x22, 0x80, 0x2f, 0x9b, 0xc2, 0x1c, 0xbe,
	0xef, 0x49, 0x1d, 0x10, 0xc1, 0x2b, 0x92, 0xdf, 0x14, 0x3a, 0x91, 0xf3, 0xd8, 0x8d, 0xf9, 0x5f,
	0xbc, 0x80, 0xc1, 0x47, 0x29, 0xd7, 0x25, 0x70, 0x07, 0x6e, 0x96, 0xb2, 0x3c, 0x88, 0xdd, 0x2c,
	0x15, 0x4f, 0x70, 0xfb, 0x99, 0x72, 0x32, 0x64, 0x91, 0x98, 0x34, 0x86, 0xd0, 0xd3, 0xfb, 0xd5,
	0x8a, 0xb4, 0x66, 0xaa, 0x1f, 0xd7, 0xa1, 0xf8, 0x0a, 0x60, 0xa1, 0xd9, 0xde, 0xfc, 0x91, 0x0a,
	0x5f, 0xc2, 0xe0, 0x57, 0xa6, 0xb4, 0xd9, 0x26, 0x1b, 0xaa, 0xce, 0x6b, 0x12, 0x38, 0x84, 0x7e,
	0x9e, 0x54, 0xa2, 0xcb, 0xe2, 0x31, 0x16, 0x1f, 0xe0, 0xf6, 0x47, 0x91, 0x26, 0x75, 0xcb, 0xdd,
	0xf9, 0x4c, 0xf8, 0x0a, 0xbc, 0xa5, 0x94, 0x6b, 0x2e, 0x0c, 0x26, 0x41, 0xb9, 0xef, 0x98, 0x69,
	0x16, 0xc4, 0x1b, 0xe8, 0xd5, 0xb5, 0x35, 0xeb, 0x5c, 0x65, 0xf5, 0x75, 0xf6, 0x9f, 0x03, 0x9e,
	0x0d, 0xed, 0x44, 0x8b, 0xe3, 0x44, 0x8b, 0x14, 0x1f, 0xc0, 0x37, 0x99, 0xc9, 0xeb, 0x5d, 0xca,
	0x00, 0x23, 0x08, 0x52, 0xd2, 0x2b, 0x95, 0x15, 0x26, 0x93, 0xdb, 0xb0, 0xcb, 0x5a, 0x3b, 0x85,
	0x4f, 0x70, 0x93, 0xf0, 0x75, 0x85, 0x1e, 0xf7, 0xbc, 0x6f, 0xf5, 0x2c, 0xef, 0x31, 0xae, 0x00,
	0x7b, 0x98, 0xa2, 0x9c, 0x12, 0x4d, 0x3f, 0x29, 0x51, 0xa1, 0x1f, 0x39, 0x8f, 0x7e, 0xdc, 0x4e,
	0x89, 0x11, 0xf4, 0x6d, 0xdd, 0xb7, 0x4c, 0x1b, 0x7c, 0x0d, 0xbe, 0x9d, 0xd8, 0xbe, 0x51, 0xf7,
	0x7c, 0x97, 0x52, 0x99, 0xfc, 0x75, 0xcb, 0x77, 0x67, 0xcf, 0xe0, 0x18, 0xe0, 0x93, 0xa2, 0xea,
	0xd2, 0xf1, 0xae, 0xcd, 0xd3, 0x6e, 0x78, 0x1a, 0x6b, 0xd1, 0xc1, 0x11, 0xf4, 0xe6, 0x64, 0x18,
	0x7e, 0xde, 0x12, 0xd9, 0x44, 0x17, 0xf0, 0x29, 0x04, 0x73, 0x32, 0xb3, 0x3c, 0xe7, 0x8e, 0x58,
	0xef, 0xd9, 0x38, 0x73, 0xf8, 0xac, 0x55, 0x63, 0x57, 0x10, 0x1d, 0x7c, 0x07, 0xd0, 0x18, 0x01,
	0x1f, 0x2a, 0xe0, 0xc4, 0x1b, 0x17, 0x5a, 0xbd, 0x07, 0x68, 0x1c, 0x7b, 0x61, 0xb8, 0xfa, 0x9c,
	0x13, 0x5b, 0x8b, 0xce, 0xf2, 0x86, 0xd3, 0xd3, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xca, 0x90,
	0x77, 0x53, 0x4b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookstoreClient is the client API for Bookstore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookstoreClient interface {
	CreateBook(ctx context.Context, in *BookReq, opts ...grpc.CallOption) (*BookRes, error)
	GetBook(ctx context.Context, in *BookQuery, opts ...grpc.CallOption) (*BookRes, error)
	GetAllBooks(ctx context.Context, in *EmptyQuery, opts ...grpc.CallOption) (*BookList, error)
	UpdateBook(ctx context.Context, in *UpdateBookReq, opts ...grpc.CallOption) (*BookRes, error)
	DeleteBook(ctx context.Context, in *BookQuery, opts ...grpc.CallOption) (*DeleteBookRes, error)
}

type bookstoreClient struct {
	cc *grpc.ClientConn
}

func NewBookstoreClient(cc *grpc.ClientConn) BookstoreClient {
	return &bookstoreClient{cc}
}

func (c *bookstoreClient) CreateBook(ctx context.Context, in *BookReq, opts ...grpc.CallOption) (*BookRes, error) {
	out := new(BookRes)
	err := c.cc.Invoke(ctx, "/proto.Bookstore/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) GetBook(ctx context.Context, in *BookQuery, opts ...grpc.CallOption) (*BookRes, error) {
	out := new(BookRes)
	err := c.cc.Invoke(ctx, "/proto.Bookstore/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) GetAllBooks(ctx context.Context, in *EmptyQuery, opts ...grpc.CallOption) (*BookList, error) {
	out := new(BookList)
	err := c.cc.Invoke(ctx, "/proto.Bookstore/GetAllBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) UpdateBook(ctx context.Context, in *UpdateBookReq, opts ...grpc.CallOption) (*BookRes, error) {
	out := new(BookRes)
	err := c.cc.Invoke(ctx, "/proto.Bookstore/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) DeleteBook(ctx context.Context, in *BookQuery, opts ...grpc.CallOption) (*DeleteBookRes, error) {
	out := new(DeleteBookRes)
	err := c.cc.Invoke(ctx, "/proto.Bookstore/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookstoreServer is the server API for Bookstore service.
type BookstoreServer interface {
	CreateBook(context.Context, *BookReq) (*BookRes, error)
	GetBook(context.Context, *BookQuery) (*BookRes, error)
	GetAllBooks(context.Context, *EmptyQuery) (*BookList, error)
	UpdateBook(context.Context, *UpdateBookReq) (*BookRes, error)
	DeleteBook(context.Context, *BookQuery) (*DeleteBookRes, error)
}

// UnimplementedBookstoreServer can be embedded to have forward compatible implementations.
type UnimplementedBookstoreServer struct {
}

func (*UnimplementedBookstoreServer) CreateBook(ctx context.Context, req *BookReq) (*BookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (*UnimplementedBookstoreServer) GetBook(ctx context.Context, req *BookQuery) (*BookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBookstoreServer) GetAllBooks(ctx context.Context, req *EmptyQuery) (*BookList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBooks not implemented")
}
func (*UnimplementedBookstoreServer) UpdateBook(ctx context.Context, req *UpdateBookReq) (*BookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (*UnimplementedBookstoreServer) DeleteBook(ctx context.Context, req *BookQuery) (*DeleteBookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}

func RegisterBookstoreServer(s *grpc.Server, srv BookstoreServer) {
	s.RegisterService(&_Bookstore_serviceDesc, srv)
}

func _Bookstore_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bookstore/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).CreateBook(ctx, req.(*BookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bookstore/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).GetBook(ctx, req.(*BookQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_GetAllBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).GetAllBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bookstore/GetAllBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).GetAllBooks(ctx, req.(*EmptyQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bookstore/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).UpdateBook(ctx, req.(*UpdateBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bookstore/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).DeleteBook(ctx, req.(*BookQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bookstore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Bookstore",
	HandlerType: (*BookstoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _Bookstore_CreateBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _Bookstore_GetBook_Handler,
		},
		{
			MethodName: "GetAllBooks",
			Handler:    _Bookstore_GetAllBooks_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _Bookstore_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Bookstore_DeleteBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/store.proto",
}
